<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	# Cu rent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- wrapper -->
	<div id="wrapper">

		<!-- Header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<?php /*
		<!-- lang switcher -->
			<ul id="page_lang_selector" class="page_lang_selector">
				<li id="lang_globe"><i class="fa fa-globe"></i></li>
				<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
				<li><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
				<?php }// end foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) ?>
			</ul>
		*/ ?>

		<!-- Main -->
			<div id="main">
				<h1 class="hide">Numisdata</h1>
				<div class="inner">
					<section class ="parallax" >
						<img src="./tpl/assets/images/Fondo.png" alt="Fondo">
						<img src="./tpl/assets/images/frente1.png" alt="Frente">
					</section>
					<section class="section">

						<img src="./tpl/assets/images/05675a00.jpg" alt="moneda">
						<!-- body text -->
						<p class ><em>Base de datos de monedas orientadas a la zona de la Mauritania Antigua</em></p>
					</section>
				</div>
			</div>

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	main_home.set_up({
		
	})
})
</script>